export type Restaurant = {
  id: string;
  update_date: string;
  name: string;
  name_kana: string;
  latitude: string;
  longitude: string;
  category: string;
  url: string;
  url_mobile: string;
  coupon_url: Record<string, any>[];
  image_url: Record<string, any>[];
  address: string;
  tel: string;
  tel_sub: string;
  fax: string;
  opentime: string;
  holiday: string;
  access: Record<string, any>[];
  parking_lots: string;
  pr: Record<string, any>[];
  code: Record<string, any>[];
  budget: number;
  party: string;
  lunch: string;
  credit_card: string;
  e_money: string;
  flags: Record<string, any>[];
};
